package_rename_config:
  android:
    app_name: startUpKit
    package_name: com.startUpKit
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: startUpKit
    bundle_name:
    package_name: com.startUpKit